name: SSR-Proxy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSR
        run: |
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo systemctl start docker
          docker run -d --name ssr-with-net-speeder -p 8989:8989 malaohu/ssr-with-net-speeder -s 0.0.0.0 -p 8989 -k 123456 -m aes-256-cfb -o plain -O origin
      - name: Run a multi-line script
        run: |
          wget https://github.com/fatedier/frp/releases/download/v0.36.2/frp_0.36.2_linux_amd64.tar.gz
          tar xzvf frp_0.36.2_linux_amd64.tar.gz
          cd frp_0.36.2_linux_amd64
          echo "[common]
          server_addr = 132.226.23.125
          server_port = 7000
          token = freefrp.net
          
          [adhuafcwess]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 8989
          remote_port = 42976" > frpc.ini
          setsid ./frpc -c ./frpc.ini
          sleep 5h
          git config --global user.name "Github Actions"
          git config --global user.email "mail@mail.org"
          git init
          git add README.md
          git commit -m "first commit"
          git branch -M main
          git remote add origin https://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@github.com/axpvlast/ActionsProxy
          git push -u origin main
